services:
  backend:
    build: ./backend
    env_file: .env
    networks:
      - default
      - db-net
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  db-net:
    external: true
    name: options-data_default
